### ISSUE TITLE
Doesn't compile due to PKERB_CLOUD_KERBEROS_DEBUG_DATA maybe?

### ISSUE THREAD

**Issue by trickster0** [EvanMcBroom/lsa-whisperer#4]
Hey you sure this compiles for you?
At least I cannot find any reference about this PKERB_CLOUD_KERBEROS_DEBUG_DATA.
I am getting a bunch of errors when it tries to compile kerberos.cpp

Nice work nevertheless dude!

**Comment by trickster0** [comment]
I never use cmake so I could be messing up but take a look either way :D

**Comment by EvanMcBroom** [comment]
Thanks for giving the project a try! I believe if you install the latest Windows 11 SDK (version 10.0.22621.0 or higher) that the issue will get resolved.

**Comment by trickster0** [comment]
Hmm, I did...Ahh I had 3 different SDKs so I had to define it.
Great stuff dude!

**Comment by EvanMcBroom** [comment]
Oh, gotcha! That makes sense. I'm glad it's working for you! 🙂
